# Generated by Django 3.1.4 on 2021-01-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='GHRCE_Konverge_Website/static/img')),
                ('image_name', models.CharField(default='<django.db.models.fields.files.ImageField>', max_length=50)),
                ('blog_name', models.CharField(default='', max_length=100)),
                ('subtitle', models.CharField(default='', max_length=50)),
                ('short_description', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=2000)),
                ('link_read_more', models.CharField(default='blog/', max_length=80)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='all_research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='GHRCE_Konverge_Website/static/img')),
                ('image_name', models.CharField(default='<django.db.models.fields.files.ImageField>', max_length=50)),
                ('research_name', models.CharField(default='', max_length=50)),
                ('subtitle', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('link_read_more', models.CharField(default='#', max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('email', models.EmailField(default='user@domain', max_length=100)),
                ('subject', models.CharField(default='Subject', max_length=200)),
                ('description', models.CharField(default='Description', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='m_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_image', models.ImageField(default='', upload_to='GHRCE_Konverge_Website/static/img')),
                ('image_name', models.CharField(default='<django.db.models.fields.files.ImageField>', max_length=50)),
                ('member_name', models.CharField(default='', max_length=50)),
                ('position', models.CharField(default='', max_length=50)),
                ('company', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('read_more', models.CharField(default='#', max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='main_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='GHRCE_Konverge_Website/static/img')),
                ('image_name', models.CharField(default='<django.db.models.fields.files.ImageField>', max_length=50)),
                ('project_name', models.CharField(default='', max_length=50)),
                ('subtitle', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('link_read_more', models.CharField(default='#', max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='mentors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='GHRCE_Konverge_Website/static/img')),
                ('image_name', models.CharField(default='<django.db.models.fields.files.ImageField>', max_length=50)),
                ('mentor_name', models.CharField(max_length=50)),
                ('position', models.CharField(default='', max_length=50)),
                ('company', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('read_more', models.CharField(default='#', max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='related_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='GHRCE_Konverge_Website/static/img')),
                ('image_name', models.CharField(default='<django.db.models.fields.files.ImageField>', max_length=50)),
                ('project_name', models.CharField(default='', max_length=50)),
                ('subtitle', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('link_read_more', models.CharField(default='#', max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
