# Generated by Django 3.1.4 on 2021-01-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_research',
            name='link_read_more',
            field=models.CharField(default='research/', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(default='Hello User', max_length=1000),
        ),
        migrations.AlterField(
            model_name='main_project',
            name='link_read_more',
            field=models.CharField(default='project/', max_length=50),
        ),
        migrations.AlterField(
            model_name='related_project',
            name='link_read_more',
            field=models.CharField(default='r_project/', max_length=50),
        ),
    ]
