# Generated by Django 3.1.4 on 2021-01-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210120_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_blog',
            name='blog_number',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='all_research',
            name='research_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main_project',
            name='project_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='related_project',
            name='project_number',
            field=models.IntegerField(default=0),
        ),
    ]
