# Generated by Django 3.1.4 on 2021-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210120_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_blog',
            old_name='blog_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='all_research',
            old_name='research_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='all_research',
            old_name='research_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='main_project',
            old_name='project_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='main_project',
            old_name='project_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='related_project',
            old_name='project_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='related_project',
            old_name='project_name',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='related_project',
            old_name='image_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='all_blog',
            name='blog_number',
        ),
        migrations.AddField(
            model_name='all_blog',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
