# Generated by Django 3.1.4 on 2021-02-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210120_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='related_project',
            name='project',
        ),
        migrations.AddField(
            model_name='all_research',
            name='short_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='main_project',
            name='short_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='related_project',
            name='image_name',
            field=models.CharField(default='<django.db.models.fields.files.ImageField>', max_length=50),
        ),
        migrations.AddField(
            model_name='related_project',
            name='short_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='all_research',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='main_project',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='related_project',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='related_project',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
